from .total import TotalViewSet
from .estoque import EstoqueViewSet
from .demandas import DemandasViewSet
from .contribuicoes import ContribuicoesViewSet
from .retiradas import RetiradasViewSet
from .retirarEstoque import RetirarEstoqueViewSet
from .entradasEstoque import EntradasEstoqueViewSet
from .contribuicoes import ContribuinteViewSet
from .login import loginViewSet
