# Generated by Django 5.0.4 on 2024-04-23 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabricaNeeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contribuicoes',
            options={'verbose_name': 'Contribuição', 'verbose_name_plural': 'Contribuições'},
        ),
    ]
