# Generated by Django 5.0.4 on 2024-04-23 15:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabricaNeeds', '0003_contribuinte_alter_contribuicoes_contribuinte'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribuicoes',
            name='data',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
