# Generated by Django 5.0.4 on 2024-04-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabricaNeeds', '0006_alter_total_options_retiradas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Estoque',
            },
        ),
    ]
