# Generated by Django 5.0.4 on 2024-04-23 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabricaNeeds', '0008_retirarestoque'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='retirarestoque',
            options={'verbose_name': 'Retirada de Estoque', 'verbose_name_plural': 'Retiradas de Estoque'},
        ),
        migrations.AddField(
            model_name='retirarestoque',
            name='produto',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fabricaNeeds.estoque'),
        ),
    ]
