# Generated by Django 5.0.4 on 2024-04-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabricaNeeds', '0009_alter_retirarestoque_options_retirarestoque_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demandas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField()),
                ('data', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Demanda',
                'verbose_name_plural': 'Demandas',
            },
        ),
    ]
