# Generated by Django 5.0.4 on 2024-04-23 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabricaNeeds', '0010_demandas'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradasEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('data', models.DateField(auto_now_add=True)),
                ('demanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabricaNeeds.demandas')),
            ],
            options={
                'verbose_name': 'Entrada de Estoque',
                'verbose_name_plural': 'Entradas de Estoque',
            },
        ),
    ]
