# Generated by Django 5.0.4 on 2024-04-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabricaNeeds', '0012_alter_demandas_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandas',
            name='produto',
            field=models.CharField(max_length=100),
        ),
    ]
