# Generated by Django 5.0.4 on 2024-04-26 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fabricaNeeds", "0014_alter_demandas_produto"),
    ]

    operations = [
        migrations.AddField(
            model_name="contribuinte",
            name="senha",
            field=models.CharField(default="0", max_length=100),
        ),
    ]
