# Generated by Django 5.0.4 on 2024-04-26 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fabricaNeeds", "0015_contribuinte_senha"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contribuinte",
            name="cpf",
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name="contribuinte",
            name="nome",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="contribuinte",
            name="senha",
            field=models.CharField(max_length=100),
        ),
    ]
