# Generated by Django 5.0.4 on 2024-05-06 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabricaNeeds', '0016_alter_contribuinte_cpf_alter_contribuinte_nome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribuinte',
            name='senha',
        ),
    ]
