# Generated by Django 5.0.4 on 2024-05-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabricaNeeds', '0017_remove_contribuinte_senha'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribuinte',
            name='senha',
            field=models.CharField(default='1234', max_length=100),
        ),
    ]
