# Generated by Django 5.0.4 on 2024-05-07 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabricaNeeds', '0018_contribuinte_senha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribuinte',
            name='cpf',
        ),
    ]
