# Generated by Django 5.0.4 on 2024-05-12 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabricaNeeds', '0019_remove_contribuinte_cpf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contribuicoes',
        ),
    ]
